trigger:
  branches:
    include:
    - main
    exclude:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci 
    npm run build
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CmdLine@2
  inputs:
    script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/artifact
      rsync -av --exclude='{node_modules,azure-pipelines.yml,README.md,.gitignore,exclude,.artifactignore}' . $(Build.ArtifactStagingDirectory)/artifact/

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/artifact'
    publishLocation: 'pipeline'
    artifactName: 'drop'